# Generated by Django 4.2.7 on 2023-11-30 12:06

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeiJiang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('descriptio', models.CharField(max_length=254)),
                ('timestamp', models.CharField(max_length=24)),
                ('begin', models.CharField(max_length=24)),
                ('end', models.CharField(max_length=24)),
                ('altitudemo', models.CharField(max_length=254)),
                ('tessellate', models.BigIntegerField()),
                ('extrude', models.BigIntegerField()),
                ('visibility', models.BigIntegerField()),
                ('draworder', models.BigIntegerField()),
                ('icon', models.CharField(max_length=254)),
                ('fid', models.FloatField()),
                ('墩号', models.BigIntegerField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
            ],
        ),
    ]
