# Generated by Django 4.2.7 on 2023-11-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beijiang',
            name='descriptio',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
