# Generated by Django 4.2.7 on 2023-11-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_beijiang_descriptio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beijiang',
            name='altitudemo',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='beijiang',
            name='begin',
            field=models.CharField(max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='beijiang',
            name='end',
            field=models.CharField(max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='beijiang',
            name='icon',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='beijiang',
            name='timestamp',
            field=models.CharField(max_length=24, null=True),
        ),
    ]
