# Generated by Django 4.2.7 on 2023-11-30 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_beijiang_altitudemo_alter_beijiang_begin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beijiang',
            name='draworder',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='beijiang',
            name='extrude',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='beijiang',
            name='fid',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='beijiang',
            name='tessellate',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='beijiang',
            name='visibility',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='beijiang',
            name='墩号',
            field=models.BigIntegerField(null=True),
        ),
    ]
