# Generated by Django 4.2.7 on 2023-12-06 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_beijiang_draworder_alter_beijiang_extrude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BridageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('beijiang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.beijiang')),
            ],
        ),
    ]
